### ISSUE TITLE
Weight is not used

### ISSUE THREAD

**Issue by inspirit** [phg1024/BlendshapeGenerationCPP#2]
https://github.com/phg1024/BlendshapeGenerationCPP/blob/a79a18718393ffa74ba3eb4e2b3b822ae2138c0e/BlendshapeGeneration/meshdeformer.cpp#L927

Weight is not used for Distortion Cost function

**Comment by phg1024** [comment]
Thanks @inspirit . Just fixed it in https://github.com/phg1024/BlendshapeGenerationCPP/commit/1397a1b64402ab2b8875994487b1c4372a1ae022
