### ISSUE TITLE
How to download the FaceWarehouse dataset ?

### ISSUE THREAD

**Issue by yuguitao** [phg1024/BlendshapeGenerationCPP#3]
Hi, 

I found there are some dataset related to facewarehouse, su as below:
FaceWarehouse_Data_0\\Tester_1\\Blendshape\\shape_0.obj
FaceWarehouse_Data_0\\Tester_1\\TrainingPose\\pose_1.obj

Can you share the dataset ? or create a dataset directory to this project ?

**Comment by phg1024** [comment]
@yuguitao Please request a copy at http://gaps-zju.org/facewarehouse/

**Comment by yuguitao** [comment]
Thanks~

**Comment by hardianlawi** [comment]
Hi @yuguitao , did you manage to get the dataset? I am not able to open the link http://gaps-zju.org/facewarehouse/ .

**Comment by phg1024** [comment]
@hardianlawi they moved the site to http://kunzhou.net/zjugaps/facewarehouse/ recently.

**Comment by chinasilva** [comment]
i can only see it   [http://kunzhou.net/zjugaps/facewarehouse/](url) but how to download

**Comment by meherabhi** [comment]
Hi,
Did anyone manage to get the dataset?
Could you please confirm, because i want to work on this dataset if the authors are providing it.

**Comment by nihalpoosa** [comment]
Did the sell the dataset? Or What's making them not release it? Please let me know if the dataset is available
